import Script from 'next/script';

export const MarkupHelper = () => (
  // <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
  <Script id="mkup-hpr" type="application/ld+json">
    {`{ "@context": "http://schema.org", "@type": "LocalBusiness", "name": "Calli Wickes Photography", "image": "https://res.cloudinary.com/dqdjqieaz/image/upload/v1720720873/2024_06_29_37_78712fcd8d.jpg", "telephone": "813-406-0558", "email": "calliwickesphotography@gmail.com", "address": { "@type": "PostalAddress", "addressLocality": " ", "addressRegion": "Florida" }, "url": "https://www.calliwickesphotography.com/", "review": { "@type": "Review", "author": { "@type": "Person", "name": "Caitlin" }, "reviewBody": "Calli did our first family photo shoot in 2018. She captured such precious photos of us with our baby girl. I still look at these photos almost everyday. She made us feel very comfortable during the session. It was such a positive experience and I can’t wait to have Calli photograph us again next time we are in Florida." } }`}
  </Script>
);
